# Kafka with zookeeper from bitnami charts if not preinstalled, enable these
bitnami-kafka:
  enabled: true
  zookeeper:
    enabled: true
  kraft:
    enabled: false
  deleteTopicEnable: true

# Debezium kafka connector
debezium:
  enabled: true
  # fixer_container:
  #   image: mosipdev/debezium-fixer:develop
  # If kafka is preinstalled, specify how it can be reached here
  # kafka:
  #   server: "kafka:9092"

# Elasticsearch kafka connector
confluentinc:
  enabled: true
  cp-kafka-connect:
    enabled: true
    # If kafka is preinstalled, specify how it can be reached here
    # kafka:
    #   bootstrapServers: kafka.kafka:9092
    # configurationOverrides:
    #   zookeeper.connect: zookeeper:2181

# KafkaClient
kafkaClient:
  enabled: true
  # the following is when no secret is to be used from db_pass
  db_secretref: null

# Enable if you do not have Elasticsearch already installed in your cluster
bitnami-elasticsearch:
  enabled: false
